### ISSUE TITLE
插件正则规则有问题

### ISSUE THREAD

**Issue by ForgotFun** [nothingisover/typembed#1]
给博主反馈一个问题,插件的匹配这块正则好像有问题,导致一些正常的URL也会被替换成视频.

这个是我遇到问题的页面
http://www.wifidog.pro/docs.html

<p><a href="http://www.wifidog.pro/2015/01/15/wifidog-demo.html">wifidog_authserver_demo 简单部署说明</a></p>

<div id="typembed"><embed src="" allowFullScreen="true" quality="high" width="100%" height="500" allowScriptAccess="always" type="application/x-shockwave-flash"></embed></div>

<p><a href="http://www.wifidog.pro/2015/01/15/wifidog-auth-server-upgrade.html">wifidog_auth server upgrade</a></p>

<p><a href="http://www.wifidog.pro/2014/12/26/wifidog-%E6%95%99%E7%A8%8B.html">Wifidog_FAQ--part2 网关，认证服务器</a></p>

<div id="typembed"><embed src="" allowfullscreen="true" quality="high" allowscriptaccess="always" type="application/x-shockwave-flash" height="500" width="100%"></div>

<p><a href="http://www.wifidog.pro/2014/12/26/wifidog-gw-message%E9%97%AE%E9%A2%98.html">原版wifidog一个接口（gw_message）上的问题</a></p>

当出现a标签多次出现 _ 时就会触发

**Comment by nothingisover** [comment]
感谢反馈，这个问题已经修复了
